NUM_ROWS = 134510 - 810
NUM_DIMS = 8_575
BATCH_SIZE = 10_000
NP_PTS = 100
FULL_DATA_FILE = 'data/apogee.memmap'
SAMPLES_FILE = 'data/apogee_samples.memmap'
DATA_FILE = 'data/data_samples.memmap'
MIN_POINTS = 10
MIN_RADIUS = 0
MAX_DEPTH = 20
LFD_LIMIT = 2
H_MAGNITUDE = 12.2
DF_CALLS = 0
GREENGENES_FASTA_SMALL = 'data/GreenGenes/43_000.fasta'
GREENGENES_FASTA_LARGE = 'data/GreenGenes/1_mil.fasta'
GREENGENES_DATA_SMALL = 'data/GreenGenes/43_000.memmap'
GREENGENES_DATA_SMALL_SAMPLES = 'data/GreenGenes/43_000_samples.memmap'
GREENGENES_DATA_SMALL_QUERIES = 'data/GreenGenes/43_000_queries.memmap'
GREENGENES_DATA_LARGE = 'data/GreenGenes/1_mil.memmap'
GREENGENES_DATA_LARGE_SAMPLES = 'data/GreenGenes/1_mil_samples.memmap'
GREENGENES_DATA_LARGE_QUERIES = 'data/GreenGenes/1_mil_queries.memmap'
SMALL_DATA_LEN = 42_967 - 1_000
LARGE_DATA_LEN = 1_075_165 - 10_000
SEQ_LEN = 7_682
